[project]
name = "health-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "qdrant-client>=1.15.1",
    "sentence-transformers>=5.1.0",
]
